### ISSUE TITLE
Make it VS2015 compatible

### ISSUE THREAD

**Issue by MaverickTse** [yumetodo/benchmark_calc_check_degit#2]
Actually I can't compile this thing as-is using VS2015, so I have to modify extensively to make it work on my machine before debugging. As a result, I'm only making commit using the web-interface...error-prone process. Would you mind making the repo less cutting-edge?

**Comment by yumetodo** [comment]
@MaverickTse Got it. Please wait...

**Comment by yumetodo** [comment]
@MaverickTse VS2015サポートしました
